TechVesta.Web/Controllers/PlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TechVesta.Web.Controllers
{
    public class PlanController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult WebsitePlan()
        {

            return View();
        }

        public IActionResult HostingPlan()
        {
            return View();
        }

        public IActionResult SeoPlan()
        {
            return View();
        }

        public IActionResult SupportPlan()
        {
            return View();
        }
    }
}

TechVesta.Web/Controllers/SubscriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MailKit.Net.Smtp;
using MimeKit;
using Stripe;
using Stripe.Checkout;
using TechVesta.Web.DTO;
using TechVesta.Web.Helper;
using System.Text.Json;
using Microsoft.Extensions.Configuration;

namespace TechVesta.Web.Controllers
{
    public class SubscriptionController : Controller
    {
        public SubscriptionController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public ActionResult Index(decimal amount, string planName)
        {
            ViewData["Amount"] = amount;
            ViewData["PlanName"] = planName;
            ViewData["Pk"] = Configuration["IsLive"].ToString() == "false" ? StripeKey.PublishableKey_Test : StripeKey.PublishableKey_Live;
            return View();
        }

        public ActionResult Checkout()
        {
            CheckoutDTO data = JsonSerializer.Deserialize<CheckoutDTO>(Request.Form["data"][0]);
            if (data.Amount > 0)
            {
                MimeMessage message = new MimeMessage();
                message.To.Add(new MailboxAddress("Techvesta Limited", EmailSetting.emailID));
                //message.Cc.Add(new MailboxAddress(data.FullName, data.Email));
                message.From.Add(new MailboxAddress(data.FullName, data.Email));
                message.Subject = $"Payment initiated by {data.Email}";
                message.Body = new TextPart("html")
                {
                    Text = $"<span>Plan</span><p>{data.Service}</p><br/><span>Email</span><p>{data.Email}</p><br/><span>Amount</span><p>{data.Amount}</p><br/><span>Contact Number</span><p>{data.Number}</p><br/><span>Address</span><p>{data.Address}, {data.City}, {data.State}, {data.Country}</p>"
                };

                using (var client = new SmtpClient())
                {
                    client.Connect(EmailSetting.smtp, EmailSetting.port, true);
                    client.Authenticate(EmailSetting.emailID, EmailSetting.password);
                    client.Send(message);
                    client.Disconnect(true);
                }

                var domain = Request.Scheme + "://" + Request.Host.Value;
                var options = new SessionCreateOptions
                {
                    PaymentMethodTypes = new List<string>
                {
                  "card",
                },
                    LineItems = new List<SessionLineItemOptions>
                {
                  new SessionLineItemOptions
                  {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                      UnitAmount = (long?)data.Amount *100,
                      Currency = data.Currency,
                      ProductData = new SessionLineItemPriceDataProductDataOptions
                      {
                        Name = data.Service,
                      },
                    },
                    Quantity = 1,
                  },
                },
                    Mode = "payment",
                    SuccessUrl = domain + "/Subscription/PaymentCompleted?isSuccessful=true",
                    CancelUrl = domain + "/Subscription/PaymentCompleted?isSuccessful=false",
                };
                var service = new SessionService();
                Session session = service.Create(options);
                return Json(new { id = session.Id });
            }
            return null;
        }

        public ActionResult PaymentCompleted(bool isSuccessful)
        {
            ViewData["isSuccess"] = isSuccessful;
            return View();
        }
    }
}

TechVesta.Web/Views/Plan/HostingPlan.cshtml
@{
    ViewData["Title"] = "Hosting Plans";
}
    <div class="container">
        <hr>
        <br><br>
        <div class="row">
            <div class="span4">
                <div style="height:220px;width:200px;box-shadow:1px 1px 4px 3px #ccc;margin-top:20px;margin-bottom:0px;float:left;padding:20px;">
                    <center>
                        <h3 style="font-size:20px;height:50px;">Linux Plan NZD 175.00/month</h3><hr />
                        <div class="submenu">
                            Single Domain<br />
                            Unlimited Space<br />
                            Unlimited Bandwidth<br />
                            <form method="post" asp-controller="Subscription" asp-action="Index" asp-route-amount="175.00" asp-route-planName="Linux Plan">
                                <input type="hidden" name="brandimage" value="computer1.png">
                                <input type="hidden" name="support" value="Account fixation and Network security Setup Support">
                                <input type="hidden" name="amt" value="175" />
                                <input type="hidden" name="quantity" value="1" />
                                <input type="hidden" name="txtemail" placeholder="" value="" style="height:5px;border:1px solid #fff;" onChange="javascript:return checkEmail();">
                                <input type="hidden" name="validity" value="1 month" />
                                <input type="hidden" name="planvalid" value="Linux Plan" />
                                <input type="hidden" name="plan" value="ii.Diagnostic of issues iii.Clean-up and Tune-up iv.Performance Optimization v.Unlimited software support for agreement period vi.Licensed Security Software for lifetime" />
                                <input type="image" src="~/img/images/order.png" alt="Submit" class="order" style="margin-top:-20px;">
                            </form>
                        </div>
                    </center>
                </div>
            </div>
            <div class="span4">
                <div style="height:220px;width:200px;box-shadow:1px 1px 4px 3px #ccc;margin-top:20px;margin-bottom:0px;float:left;padding:20px;">
                    <center>
                        <h3 style="font-size:20px;height:50px;">Windows Plan NZD 230.00/month </h3><hr />
                        <div class="submenu">
                            Single Domain<br>
                            Unlimited Space<br>
                            Unlimited Bandwidth<br>
                            <form method="post" asp-controller="Subscription" asp-action="Index" asp-route-amount="230.00" asp-route-planName="Windows Plan">
                                <input type="hidden" name="brandimage" value="computer1.png">
                                <input type="hidden" name="support" value="Account fixation and Network security Setup Support">
                                <input type="hidden" name="amt" value="230" />
                                <input type="hidden" name="txtemail" placeholder="" value="" style="height:5px;border:1px solid #fff;" onChange="javascript:return checkEmail();">
                                <input type="hidden" name="quantity" value="1" />
                                <input type="hidden" name="validity" value="1 month" />
                                <input type="hidden" name="planvalid" value="Windows Plan" />
                                <input type="hidden" name="plan" value="ii.Diagnostic of issues iii.Clean-up and Tune-up iv.Performance Optimization v.Unlimited software support for agreement period vi.Licensed Security Software for lifetime" />
                                <input type="image" src="~/img/images/order.png" alt="Submit" class="order" style="margin-top:-20px;">
                            </form>
                        </div>
                    </center>
                </div>
            </div>
            <div class="span4">
                <div style="height:220px;width:200px;box-shadow:1px 1px 4px 3px #ccc;margin-top:20px;margin-bottom:0px;float:left;padding:20px;">
                    <center>
                        <h3 style="font-size:20px;height:50px;">E-Commerce Plan NZD 265/month</h3><hr />
                        <div class="submenu">
                            500 Product <br /><br /><br />
                            <form method="post" asp-controller="Subscription" asp-action="Index" asp-route-amount="265.00" asp-route-planName="E-Commerce Plan">
                                <input type="hidden" name="brandimage" value="computer1.png">
                                <input type="hidden" name="support" value="Account fixation and Network security Setup Support">
                                <input type="hidden" name="amt" value="265" />
                                <input type="hidden" name="quantity" value="1" />
                                <input type="hidden" name="txtemail" placeholder="" value="" style="height:5px;border:1px solid #fff;" onChange="javascript:return checkEmail();">
                                <input type="hidden" name="validity" value="1 month" />
                                <input type="hidden" name="planvalid" value="E-Commerce Plan" />
                                <input type="hidden" name="plan" value="ii.Diagnostic of issues iii.Clean-up and Tune-up iv.Performance Optimization v.Unlimited software support for agreement period vi.Licensed Security Software for lifetime" />
                                <input type="image" src="~/img/images/order.png" alt="Submit" class="order" style="margin-top:-20px;">
                            </form>
                        </div>
                    </center>
                </div>
            </div>
        </div>
        <br /><br /><br />
        <div style="text-align:center;">***All prices include 15% GST***</div>
    </div>

TechVesta.Web/Views/Plan/Index.cshtml
@{
    ViewData["Title"] = "Plans";
}
<div class="container">

    <hr>
    <br><br>
    <div class="row">
        <div class="span3">
            <center>
                <a asp-action="WebsitePlan" asp-controller="Plan"> <img src="~/img/WEBSITE.png"></a>
            </center> <br>
        </div>

        <div class="span3">
            <center>
                <a asp-action="HostingPlan" asp-controller="Plan"> <img src="~/img/webhosting.png"></a>
            </center> <br>
        </div>

        <div class="span3">
            <center>
                <a asp-action="SeoPlan" asp-controller="Plan"> <img src="~/img/SEO.png"></a>
            </center> <br>
        </div>

        <div class="span3">
            <center>
                <a asp-action="SupportPlan" asp-controller="Plan"> <img src="~/img/SUPPORT.png"></a>
            </center> <br>
        </div>
    </div>
</div>

TechVesta.Web/Views/Plan/Plans.cshtml
@{
    ViewData["Title"] = "Plans offered by TechVesta";
}
<div class="container">

    <hr>
    <br><br>
    <div class="row">
        <div class="span3">
            <center>
                <a asp-action="WebsitePlan" asp-controller="Plan"> <img src="~/img/WEBSITE.png"></a>
            </center> <br>
        </div>

        <div class="span3">
            <center>
                <a asp-action="HostingPlan" asp-controller="Plan"> <img src="~/img/webhosting.png"></a>
            </center> <br>
        </div>

        <div class="span3">
            <center>
                <a asp-action="SeoPlan" asp-controller="Plan"> <img src="~/img/SEO.png"></a>
            </center> <br>
        </div>

        <div class="span3">
            <center>
                <a asp-action="SupportPlan" asp-controller="Plan"> <img src="~/img/SUPPORT.png"></a>
            </center> <br>
        </div>
    </div>
</div>

TechVesta.Web/Views/Plan/SeoPlan.cshtml
    @{
        ViewData["Title"] = "SEO Plans";
    }
    <div class="container">

        <hr>
        <br><br>
        <div class="row">


            <div class="span4">

                <div style="height:180px;width:200px;box-shadow:1px 1px 4px 3px #ccc;margin-top:20px;margin-bottom:0px;float:left;padding:20px;">
                    <center>
                        <h3 style="font-size:20px;height:30px;">MINI Plan <br />NZD 895.00</h3>
                        <div class="submenu">
                            5 Keywords <br><br>

                            <form method="post" asp-controller="Subscription" asp-action="Index" asp-route-amount="895.00" asp-route-planName="MINI Plan">
                                <input type="hidden" name="brandimage" value="computer1.png">
                                <input type="hidden" name="support" value="Account fixation and Network security Setup Support">
                                <input type="hidden" name="amt" value="895" />
                                <input type="hidden" name="quantity" value="1" />
                                <input type="hidden" name="txtemail" placeholder="" value="" style="height:5px;border:1px solid #fff;" onChange="javascript:return checkEmail();">
                                <input type="hidden" name="validity" value="1 day" />
                                <input type="hidden" name="planvalid" value="MINI Plan" />
                                <input type="hidden" name="plan" value="ii.Diagnostic of issues iii.Clean-up and Tune-up iv.Performance Optimization v.Unlimited software support for agreement period vi.Licensed Security Software for lifetime" />
                                <input type="image" src="~/img/images/order.png" alt="Submit" class="order" style="margin-top:-20px;">
                            </form>
                        </div>
                    </center>
                </div>

            </div>

            <div class="span4">

                <div style="height:180px;width:200px;box-shadow:1px 1px 4px 3px #ccc;margin-top:20px;margin-bottom:0px;float:left;padding:20px;">
                    <center>
                        <h3 style="font-size:20px;height:30px;">STARTER Plan <br />NZD 1785.00</h3>
                        <div class="submenu">
                            10 Keywords<br><br>
                            <form method="post" asp-controller="Subscription" asp-action="Index" asp-route-amount="1785.00" asp-route-planName="STARTER Plan">
                                <input type="hidden" name="brandimage" value="computer1.png">
                                <input type="hidden" name="support" value="Account fixation and Network security Setup Support">
                                <input type="hidden" name="amt" value="1785" />
                                <input type="hidden" name="quantity" value="1" />
                                <input type="hidden" name="txtemail" placeholder="" value="" style="height:5px;border:1px solid #fff;" onChange="javascript:return checkEmail();">
                                <input type="hidden" name="validity" value="1 day" />
                                <input type="hidden" name="planvalid" value="STARTER Plan" />
                                <input type="hidden" name="plan" value="ii.Diagnostic of issues iii.Clean-up and Tune-up iv.Performance Optimization v.Unlimited software support for agreement period vi.Licensed Security Software for lifetime" />
                                <input type="image" src="~/img/images/order.png" alt="Submit" class="order" style="margin-top:-20px;">
                            </form>
                        </div>
                    </center>
                </div>

            </div>

            <div class="span4">

                <div style="height:180px;width:200px;box-shadow:1px 1px 4px 3px #ccc;margin-top:20px;margin-bottom:0px;float:left;padding:20px;">
                    <center>
                        <h3 style="font-size:20px;height:30px;">BRONZE Plan <br />NZD 2675.00</h3>
                        <div class="submenu">
                            20 Keywords<br><br>
                            <form method="post" asp-controller="Subscription" asp-action="Index" asp-route-amount="2675" asp-route-planName="BRONZE Plan">
                                <input type="hidden" name="brandimage" value="computer1.png">
                                <input type="hidden" name="support" value="Account fixation and Network security Setup Support">
                                <input type="hidden" name="amt" value="2675" />
                                <input type="hidden" name="txtemail" placeholder="" value="" style="height:5px;border:1px solid #fff;" onChange="javascript:return checkEmail();">
                                <input type="hidden" name="quantity" value="1" />
                                <input type="hidden" name="validity" value="1 day" />
                                <input type="hidden" name="planvalid" value="BRONZE Plan" />
                                <input type="hidden" name="plan" value="ii.Diagnostic of issues iii.Clean-up and Tune-up iv.Performance Optimization v.Unlimited software support for agreement period vi.Licensed Security Software for lifetime" />
                                <input type="image" src="~/img/images/order.png" alt="Submit" class="order" style="margin-top:-20px;">
                            </form>
                        </div>
                    </center>
                </div>

            </div>


        </div>
        <br><br>

        <div class="row">


            <div class="span4">
                <div style="height:180px;width:200px;box-shadow:1px 1px 4px 3px #ccc;margin-top:20px;margin-bottom:20px;float:left;padding:20px;">
                    <center>
                        <h3 style="font-size:20px;height:30px;">SILVER Plan <br />NZD 3575.00</h3>
                        <div class="submenu">
                            40 Keywords<br /><br />
                            <form method="post" asp-controller="Subscription" asp-action="Index" asp-route-amount="3575.00" asp-route-planName="SILVER Plan">
                                <input type="hidden" name="brandimage" value="computer1.png">
                                <input type="hidden" name="support" value="Account fixation and Network security Setup Support">
                                <input type="hidden" name="amt" value="3575" />
                                <input type="hidden" name="quantity" value="1" />
                                <input type="hidden" name="txtemail" placeholder="" value="" style="height:5px;border:1px solid #fff;" onChange="javascript:return checkEmail();">
                                <input type="hidden" name="validity" value="1 day" />
                                <input type="hidden" name="planvalid" value="SILVER Plan" />
                                <input type="hidden" name="plan" value="ii.Diagnostic of issues iii.Clean-up and Tune-up iv.Performance Optimization v.Unlimited software support for agreement period vi.Licensed Security Software for lifetime" />
                                <input type="image" src="~/img/images/order.png" alt="Submit" class="order" style="margin-top:-20px;">
                            </form>
                        </div>
                    </center>
                </div>
            </div>




            <div class="span4">
                <div style="height:180px;width:200px;box-shadow:1px 1px 4px 3px #ccc;margin-top:20px;margin-bottom:20px;float:left;padding:20px;">
                    <center>
                        <h3 style="font-size:20px;height:30px;">GOLD Plan <br />NZD 4355.00</h3>
                        <div class="submenu">
                            80 Keywords<br><br>
                            <form method="post" asp-controller="Subscription" asp-action="Index" asp-route-amount="4355.00" asp-route-planName="GOLD Plan">
                                <input type="hidden" name="brandimage" value="computer1.png">
                                <input type="hidden" name="support" value="Account fixation and Network security Setup Support">
                                <input type="hidden" name="amt" value="4355" />
                                <input type="hidden" name="quantity" value="1" />
                                <input type="hidden" name="txtemail" placeholder="" value="" style="height:5px;border:1px solid #fff;" onChange="javascript:return checkEmail();">
                                <input type="hidden" name="validity" value="1 day" />
                                <input type="hidden" name="planvalid" value="GOLD Plan" />
                                <input type="hidden" name="plan" value="ii.Diagnostic of issues iii.Clean-up and Tune-up iv.Performance Optimization v.Unlimited software support for agreement period vi.Licensed Security Software for lifetime" />
                                <input type="image" src="~/img/images/order.png" alt="Submit" class="order" style="margin-top:-20px;">
                            </form>
                        </div>
                    </center>
                </div>


            </div>

            <div class="span4">
                <div style="height:180px;width:200px;box-shadow:1px 1px 4px 3px #ccc;margin-top:20px;margin-bottom:20px;float:left;padding:20px;">
                    <center>
                        <h3 style="font-size:20px;height:30px;">Customize Plan <br />NZD 5355.00</h3>
                        <div class="submenu">
                            As per the requirement <br /> Plans will be customized. for 6 Months<br /><br />
                            <form method="post" asp-controller="Subscription" asp-action="Index" asp-route-amount="5355.00" asp-route-planName="Customize Plan">
                                <input type="hidden" name="brandimage" value="computer1.png">
                                <input type="hidden" name="support" value="Account fixation and Network security Setup Support">
                                <input type="hidden" name="amt" value="5355" />
                                <input type="hidden" name="quantity" value="1" />
                                <input type="hidden" name="validity" value="1 day" />
                                <input type="hidden" name="txtemail" placeholder="" value="" style="height:5px;border:1px solid #fff;" onChange="javascript:return checkEmail();">
                                <input type="hidden" name="planvalid" value="Customize Plan" />
                                <input type="hidden" name="plan" value="ii.Diagnostic of issues iii.Clean-up and Tune-up iv.Performance Optimization v.Unlimited software support for agreement period vi.Licensed Security Software for lifetime" />
                                <input type="image" src="~/img/images/order.png" alt="Submit" class="order" style="margin-top:-20px;">
                            </form>

                        </div>
                    </center>
                </div>

            </div>

            <br ?<br /><br /><div style="text-align:center;">***All prices include 15% GST***</div>
        </div>












    </div>